chore: 更新Windows构建环境和自动构建脚本版本号，优化构建流程

diff --git a/.github/workflows/windows-gcc.yml b/.github/workflows/windows-gcc.yml
--- a/.github/workflows/windows-gcc.yml
+++ b/.github/workflows/windows-gcc.yml
@@ -87,32 +87,38 @@ jobs:
           name: ${{ steps.package.outputs.packageName }}
           path: ${{ steps.package.outputs.packageName }}.zip
 
-      - name: Get version from CMakeLists.txt
+      - name: Get version from CMake
         if: github.ref == 'refs/heads/master'
         id: get_version
-        shell: bash
+        shell: pwsh
         run: |
-          version=$(grep -oP 'project\(JX3DPS VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
-          echo "version=$version" >> $GITHUB_OUTPUT
+          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release > cmake_output.txt
+          $version = (Select-String -Path cmake_output.txt -Pattern "VERSION=(.+)").Matches.Groups[1].Value
+          if ($version) {
+            echo "Extracted version: $version"
+            echo "VERSION=$version" >> $env:GITHUB_OUTPUT
+          } else {
+            echo "Failed to extract version from CMake output"
+            exit 1
+          }
 
       - name: Generate Changelog
         if: github.ref == 'refs/heads/master'
         id: changelog
+        shell: pwsh
         run: |
           npm install -g conventional-changelog-cli
-          changelog=$(conventional-changelog -p angular -r 2)
-          changelog="${changelog//'%'/'%25'}"
-          changelog="${changelog//$'\n'/'%0A'}"
-          changelog="${changelog//$'\r'/'%0D'}"
-          echo "changelog=$changelog" >> $GITHUB_OUTPUT
+          $changelog = (conventional-changelog -p angular -r 2) -join "`n"
+          $changelog = $changelog -replace '%', '%25' -replace "`n", '%0A' -replace "`r", '%0D'
+          echo "changelog=$changelog" >> $env:GITHUB_OUTPUT
 
       - name: Create Tag
         if: github.ref == 'refs/heads/master'
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-          git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"
-          git push origin v${{ steps.get_version.outputs.version }}
+          git tag -a v${{ steps.get_version.outputs.VERSION }} -m "Release v${{ steps.get_version.outputs.VERSION }}"
+          git push origin v${{ steps.get_version.outputs.VERSION }}
 
       - name: Create Release
         if: github.ref == 'refs/heads/master'
@@ -121,8 +127,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
-          tag_name: v${{ steps.get_version.outputs.version }}
-          release_name: JX3DPS v${{ steps.get_version.outputs.version }}
+          tag_name: v${{ steps.get_version.outputs.VERSION }}
+          release_name: JX3DPS v${{ steps.get_version.outputs.VERSION }}
           body: |
             ${{ steps.changelog.outputs.changelog }}
           draft: false
